// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct LumberjackContractClientProgram;
impl sails_rs::client::Program for LumberjackContractClientProgram {}
pub trait LumberjackContractClient {
    type Env: sails_rs::client::GearEnv;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> LumberjackContractClient
    for sails_rs::client::Actor<LumberjackContractClientProgram, E>
{
    type Env = E;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env> {
        self.service(stringify!(Game))
    }
}
pub trait LumberjackContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<LumberjackContractClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> LumberjackContractClientCtors
    for sails_rs::client::Deployment<LumberjackContractClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<LumberjackContractClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod game {
    use super::*;
    pub trait Game {
        type Env: sails_rs::client::GearEnv;
        fn clear_leaderboard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClearLeaderboard, Self::Env>;
        fn submit_run(
            &mut self,
            branches: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitRun, Self::Env>;
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn player_best_branches(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestBranches, Self::Env>;
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env>;
    }
    pub struct GameImpl;
    impl<E: sails_rs::client::GearEnv> Game for sails_rs::client::Service<GameImpl, E> {
        type Env = E;
        fn clear_leaderboard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::ClearLeaderboard, Self::Env> {
            self.pending_call(())
        }
        fn submit_run(
            &mut self,
            branches: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitRun, Self::Env> {
            self.pending_call((branches,))
        }
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn player_best_branches(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestBranches, Self::Env> {
            self.pending_call((player,))
        }
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env> {
            self.pending_call((player,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ClearLeaderboard () -> ());
        sails_rs::io_struct_impl!(SubmitRun (branches: u32) -> super::SubmitRunReply);
        sails_rs::io_struct_impl!(Leaderboard (limit: u32) -> Vec<super::LeaderboardEntry>);
        sails_rs::io_struct_impl!(PlayerBestBranches (player: ActorId) -> u32);
        sails_rs::io_struct_impl!(PlayerRank (player: ActorId) -> Option<u32>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum GameEvents {
            BestRunUpdated { player: ActorId, branches: u32 },
            LeaderboardCleared { by: ActorId },
        }
        impl sails_rs::client::Event for GameEvents {
            const EVENT_NAMES: &'static [Route] = &["BestRunUpdated", "LeaderboardCleared"];
        }
        impl sails_rs::client::ServiceWithEvents for GameImpl {
            type Event = GameEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SubmitRunReply {
    pub best_branches: u32,
    pub improved: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderboardEntry {
    pub player: ActorId,
    pub branches: u32,
}
