// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct Game2048ContractClientProgram;
impl sails_rs::client::Program for Game2048ContractClientProgram {}
pub trait Game2048ContractClient {
    type Env: sails_rs::client::GearEnv;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Game2048ContractClient
    for sails_rs::client::Actor<Game2048ContractClientProgram, E>
{
    type Env = E;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env> {
        self.service(stringify!(Game))
    }
}
pub trait Game2048ContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<Game2048ContractClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> Game2048ContractClientCtors
    for sails_rs::client::Deployment<Game2048ContractClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<Game2048ContractClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod game {
    use super::*;
    pub trait Game {
        type Env: sails_rs::client::GearEnv;
        fn submit_score(
            &mut self,
            score: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitScore, Self::Env>;
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn player_best_score(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestScore, Self::Env>;
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env>;
        fn scores_count(&self) -> sails_rs::client::PendingCall<io::ScoresCount, Self::Env>;
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env>;
    }
    pub struct GameImpl;
    impl<E: sails_rs::client::GearEnv> Game for sails_rs::client::Service<GameImpl, E> {
        type Env = E;
        fn submit_score(
            &mut self,
            score: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitScore, Self::Env> {
            self.pending_call((score,))
        }
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn player_best_score(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestScore, Self::Env> {
            self.pending_call((player,))
        }
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env> {
            self.pending_call((player,))
        }
        fn scores_count(&self) -> sails_rs::client::PendingCall<io::ScoresCount, Self::Env> {
            self.pending_call(())
        }
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(SubmitScore (score: u32) -> super::SubmitScoreReply);
        sails_rs::io_struct_impl!(Leaderboard (limit: u32) -> Vec<super::LeaderboardEntry>);
        sails_rs::io_struct_impl!(PlayerBestScore (player: ActorId) -> u32);
        sails_rs::io_struct_impl!(PlayerRank (player: ActorId) -> Option<u32>);
        sails_rs::io_struct_impl!(ScoresCount () -> u32);
        sails_rs::io_struct_impl!(Version () -> String);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum GameEvents {
            BestScoreUpdated { player: ActorId, score: u32 },
        }
        impl sails_rs::client::Event for GameEvents {
            const EVENT_NAMES: &'static [Route] = &["BestScoreUpdated"];
        }
        impl sails_rs::client::ServiceWithEvents for GameImpl {
            type Event = GameEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SubmitScoreReply {
    pub best_score: u32,
    pub improved: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderboardEntry {
    pub player: ActorId,
    pub score: u32,
}
