// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ContractClientProgram;
impl sails_rs::client::Program for ContractClientProgram {}
pub trait ContractClient {
    type Env: sails_rs::client::GearEnv;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClient
    for sails_rs::client::Actor<ContractClientProgram, E>
{
    type Env = E;
    fn game(&self) -> sails_rs::client::Service<game::GameImpl, Self::Env> {
        self.service(stringify!(Game))
    }
}
pub trait ContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ContractClientCtors
    for sails_rs::client::Deployment<ContractClientProgram, E>
{
    type Env = E;
    fn create(self) -> sails_rs::client::PendingCtor<ContractClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod game {
    use super::*;
    pub trait Game {
        type Env: sails_rs::client::GearEnv;
        fn submit_run(
            &mut self,
            run_id: String,
            height: u32,
            score: u32,
            duration_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SubmitRun, Self::Env>;
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn player_best_height(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestHeight, Self::Env>;
        fn player_best_run(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestRun, Self::Env>;
        fn player_points(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerPoints, Self::Env>;
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env>;
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env>;
    }
    pub struct GameImpl;
    impl<E: sails_rs::client::GearEnv> Game for sails_rs::client::Service<GameImpl, E> {
        type Env = E;
        fn submit_run(
            &mut self,
            run_id: String,
            height: u32,
            score: u32,
            duration_ms: u64,
        ) -> sails_rs::client::PendingCall<io::SubmitRun, Self::Env> {
            self.pending_call((run_id, height, score, duration_ms))
        }
        fn leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn player_best_height(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestHeight, Self::Env> {
            self.pending_call((player,))
        }
        fn player_best_run(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerBestRun, Self::Env> {
            self.pending_call((player,))
        }
        fn player_points(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerPoints, Self::Env> {
            self.pending_call((player,))
        }
        fn player_rank(
            &self,
            player: ActorId,
        ) -> sails_rs::client::PendingCall<io::PlayerRank, Self::Env> {
            self.pending_call((player,))
        }
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(SubmitRun (run_id: String, height: u32, score: u32, duration_ms: u64) -> super::SubmitRunReply);
        sails_rs::io_struct_impl!(Leaderboard (limit: u32) -> Vec<super::LeaderboardEntry>);
        sails_rs::io_struct_impl!(PlayerBestHeight (player: ActorId) -> u32);
        sails_rs::io_struct_impl!(PlayerBestRun (player: ActorId) -> Option<super::RunRecord>);
        sails_rs::io_struct_impl!(PlayerPoints (player: ActorId) -> u128);
        sails_rs::io_struct_impl!(PlayerRank (player: ActorId) -> Option<u32>);
        sails_rs::io_struct_impl!(Version () -> String);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum GameEvents {
            BestRunUpdated {
                run_id: String,
                player: ActorId,
                height: u32,
                score: u32,
                points: u128,
            },
        }
        impl sails_rs::client::Event for GameEvents {
            const EVENT_NAMES: &'static [Route] = &["BestRunUpdated"];
        }
        impl sails_rs::client::ServiceWithEvents for GameImpl {
            type Event = GameEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SubmitRunReply {
    pub run: RunRecord,
    pub player_points: u128,
    pub best_height: u32,
    pub improved: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RunRecord {
    pub run_id: String,
    pub player: ActorId,
    pub height: u32,
    pub score: u32,
    pub duration_ms: u64,
    pub points_awarded: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderboardEntry {
    pub player: ActorId,
    pub points: u128,
    pub best_height: u32,
}
